### ISSUE TITLE
Use standard theme installation

### ISSUE THREAD

**Issue by dakrone** [thblt/eziam-theme-emacs#12]
Currently the only way to load the theme is to `(require 'eziam-light-theme)` (or dark), trying to use `load-theme` does not list eziam in the list of candidates.

Would it be possible to fix the package so that `eziam-light` and `eziam-dark` show up in the list when using `load-theme`? This would allow users to do `(load-theme 'eziam-light t)` in their init files.

**Comment by thblt** [comment]
I can reproduce this from `emacs -Q`, but I don't really understand why it happens, though.  I'll look into it when I'll find the time.  In the meantime, a workaround would be to add Eziam directory to `custom-theme-load-path`.  Thanks a lot for reporting this, this is a serious usability problem.

**Comment by thblt** [comment]
OK, I think I got it:  I assumed package.el would automatically update `custom-theme-load-path` to match installed packages, but it doesn't.  I'll have to add this to Eziam;  I expect to be able to do it tonight (@GMT+1).

**Comment by thblt** [comment]
I believe b34a9d15a450a50e83301f71effe146a5a64c0ee should fix the issue.  Could you please confirm? The changes should be on Melpa in a few hours.

**Comment by dakrone** [comment]
Thibault writes:

>    I believe [1]b34a9d1 should fix the issue. Could you please
>    confirm? The changes should be on Melpa in a few hours.

That seems to work great, thanks!
--
;; Lee
