### ISSUE TITLE
rainbow-3 is too bright in light version

### ISSUE THREAD

**Issue by serg-kozhemyakin** [thblt/eziam-theme-emacs#13]
by default it set to yellow that is too bright from my pov on gray background. locally i modified it to 'goldenrod' that looks more comfortable from my pov. 

compare default
![yellow](https://user-images.githubusercontent.com/11452776/30479057-21fda12c-9a1c-11e7-8881-a464c70b2af0.png)
vs.
![goldenrod](https://user-images.githubusercontent.com/11452776/30479113-6dda3a1a-9a1c-11e7-8cf2-7ba7a76cf3ff.png)

maybe goldenrod is not best choice here but definitely better then bright yellow from my pov.

**Comment by thblt** [comment]
Good suggestion, thanks! Could you please send a PR?
