### ISSUE TITLE
Symbol's function definition is void: string

### ISSUE THREAD

**Issue by armaansood** [thblt/eziam-theme-emacs#18]
After installing via the elpa package manager, I can't launch the theme from customize-themes - the minibuffer error is "Symbol's function definition is void: string"

**Comment by thblt** [comment]
I'm sorry, I can't reproduce this.  I've tried running `emacs -q`, evaluating:

``` elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(package-list-packages)
(package-install 'eziam-theme)
```

then `M-x customize-themes`.  On the Customize UI, I can click on the three Eziam variants to activate them.

**Comment by armaansood** [comment]
I followed the same steps and it doesn't work for me (on Ubuntu), but I managed to fix it by adding the following to my init

`(defalias 'string> 'string-greaterp)
(defun string-greaterp (string1 string2)
(string-lessp string2 string1))`

**Comment by thblt** [comment]
Wait, is the missing function `string` or `string>`?

**Comment by armaansood** [comment]
I should've been more clear: it's "string>"

**Comment by thblt** [comment]
What are your Emacs and Ubuntu versions please?

**Comment by armaansood** [comment]
"GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-20 on lcy01-07, modified by Debian" is what I get when I type the command "emacs-version"

My Ubuntu version is 16.04.4 LTS (https://i.imgur.com/U9b4v0o.png)

**Comment by thblt** [comment]
Indeed, `string>` doesn't exist in Emacs 24.x, I didn't know that.   Your solution is correct, I'll push a fix soon to use string-lessp instead.  Thanks!
