### ISSUE TITLE
Is not working with use-package

### ISSUE THREAD

**Issue by fernando-jascovich** [thblt/eziam-theme-emacs#19]
When you try to load the package using `use-package`, it throws the following error: 

> Error (use-package): Cannot load eziam-theme

Please check this ascineema with a dummy (and plain) usage:
https://asciinema.org/a/6uujeCyXq3YBVeGjoO7GY0Lyl

**Comment by thblt** [comment]
Hi, thanks for the very detailed report.  The issue here is that eziam-theme doesn't exist : the themes are called eziam-light and eziam-dark.

**Comment by thblt** [comment]
Ignore my previous message, I misread the code. I'll try and look into this later today.

**Comment by thblt** [comment]
I think my original answer is actually correct.  The eziam-theme package doesn't provide an `eziam-theme.el`, and the use-package stanza expands to something with (require 'eziam-theme).  These should work:

```elisp
(use-package eziam-theme
    :defer t
    :init (load-theme 'eziam-dark))
```

```elisp
(use-package eziam-dark-theme
    :ensure eziam-theme))
```

**Comment by fernando-jascovich** [comment]
Indeed your original answer is right. And your proposed workaround works perfect!
Thanks!
P.S.: Thanks for the great work on the themes; once they are activated, there is no turning back.
