### ISSUE TITLE
color-comments for dusk-theme and heading scaling for gray-blocks

### ISSUE THREAD

**Issue by gusbrs** [thblt/eziam-theme-emacs#22]
Hi Thibault,

I really like this new theme of yours, thanks for making it available.

While testing, I noticed a couple of things, which I might as well report.

Testing the `dusk-theme` I get a missing `color-comments` variable. Backtrace when trying to load "eziam-dusk":

> Debugger entered--Lisp error: (void-variable colored-comments)
  eziam-apply-custom-theme(eziam-dusk)

Indeed, it seems to be missing in the `eziam-with-color-variables` "Misc" block in `eziam-dusk-theme.el`.

Second thing is that heading scaling is currently hardcoded for the `gray-blocks` heading style. Thus, the defcustom `eziam-scale-headings` is not honored when set to nil.

Thanks again. And long live Eziam.

**Comment by thblt** [comment]
Thanks! Everything should be fixed now.

**Comment by gusbrs** [comment]
Thank you!
