### ISSUE TITLE
org-agenda, tasks look like one big chunk

### ISSUE THREAD

**Issue by BubblesToTheLimit** [thblt/eziam-theme-emacs#8]
Really awesome skin! I have seen alot of skins but this grayscale theme is kind of a new take on themes in general, everything seems to fit.

Can I ask for a favor to make the org-agenda entries more distinguishable? Zenburn for example marks Todos for today in blue so they are highlighted really nicely and with eziam I cant even find these tasks.

**Comment by thblt** [comment]
Thanks!

Would something like this be good for you?  I don't use org-agenda much (yet), so I assumed this was the view you were referring to.  

![2017-01-20-004653_1148x716_scrot](https://cloud.githubusercontent.com/assets/2453136/22130036/0ac6b8e6-deaa-11e6-85d5-803f4a8b6e85.png)

The change isn't in the repo yet, I was just experimenting with customize-face.  If it works for you, I'll try to commit this tomorrow.

**Comment by BubblesToTheLimit** [comment]
Yes this looks better, thank you! :+1:  :)

**Comment by thblt** [comment]
Thanks, will merge this tonight!

**Comment by thblt** [comment]
(Sorry, I'm late.  I haven't forgotten, but my notes on the above screenshot are on another computer.  I'll try to do this tonight)

**Comment by thblt** [comment]
Done, sorry for the delay.  Could you test this with your own data and tell me if it's good for you?

**Comment by BubblesToTheLimit** [comment]
Yes it's better now, thanks! 👍
